
name: veloxfusion_cobranca
description: Cobrança automática IPTV via WhatsApp
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  http: ^0.13.4
  intl: ^0.17.0
